### ISSUE TITLE
datetime limited to full minutes only ?

### ISSUE THREAD

**Issue by Gys** [wumke/react-native-local-notifications#10]
The readme says: The date + time to show the notification, as a string in the format 'yyyy-mm-dd hh:mm'

And indeed I am not able to add seconds. Is there a reason for this limitation ? From the Apple docs I understand that seconds (even milliseconds) should be possible ?

I want to use local notifications for timing sub-minute events. So its important to have seconds support and I wonder if that is possible at all.

**Comment by wumke** [comment]
I've noticed that android (or at least some versions of android) display the notifications somewhere in the minute after it has been specified. It seems that when they are created at for example 14:00:15 and set to display at 14:30, they pop up at 14:30:15... reason unknown and not further investigated because it's fine for me. 
Another reason why I think minute intervals are good enough is that you do not want to annoy your users to often... :-) 

For your specific use case, does it make sense to send only a notification when the event is done with the duration of the event? It seems to me that you want to know the duration, when looking to your notifications periodically, so why don't you just keep a log file/table in your app? In case of a lot of events your notification screen will be spammed all over!

Anyway, feel free to update the code and send me a pull request such that if seconds are given, they are used and else ignored/default 00... I will then merge it in next release! 
FYI: the reason why i chose to use text is that no conversion is needed when setting notification based on cloud-fetched json data, and that every date/time helper package should be able to export to a string. 
(For pull requests: solution must work on both, iOS and android, or at least degrade gracefully without losing major functionality. I really hate packages that have ios and android specific configuration in it...)
