### ISSUE TITLE
not working on iOS 

### ISSUE THREAD

**Issue by cinder92** [wumke/react-native-local-notifications#11]
Hello i was just installed this plugin, i set the code to 

```
RNLocalNotifications.createNotification(1,'Some Text', '2018-02-15 21:05', 'default');
```

but nothing happens at that time, i just set the app to background (i mean i pressed the home button) then no notification appear, also, i haven't receive the warning of "Do you want to receive notifications?"

any idea?

RN v : 0.53.0
device : iPhone 8 Simulator (yes, you can receive local notification here)
platform : Mac

**Comment by wumke** [comment]
I'm using it in RN versions up to 0.48 without problems, always on real devices.
The notifications warning you describe only appears when push notifications are enabled, local notifications do not need confirmation, so that is no issue.

What do the logs tell you when you set the notification, and when it should trigger? Any clue to find there?
Did you add Alarm.caf and Silence.caf to the Resources folder of your xcode project? (can be found in react-native-local-notifications/ios/RNLocalNotifications)
Is the simulator in some 'Do not disturb mode'?

**Comment by cinder92** [comment]
@wumke thanks for answer, nope, the simulator is not in `don't disturb mode`, there is no logs, nothing about notification...

**Comment by gazzwi86** [comment]
Amy news on this?  I'm getting the same issue at the moment.  I'm on RN 0.52.0, and in the simulator, I'm not noticing anything in the log regarding notifications

**Comment by wumke** [comment]
Not from my side... what is the result when you try on real devices?
To debug you can also try and add logs in native code!

**Comment by gazzwi86** [comment]
I don't have my cable with me atm.  I managed to get `react-native-notifications` working on simulator though.

**Comment by wumke** [comment]
@gazzwi86 : What was the issue/did you change?

**Comment by cinder92** [comment]
thanks, im not using this repo anymore
