### ISSUE TITLE
onNotification problem (Android)

### ISSUE THREAD

**Issue by enigmasteron** [wumke/react-native-local-notifications#23]
I use react-native-push-notification, for handle onNotification event to get hiddendata. Works fine on ios but on android onNotification method not trigger.

Thanks

**Comment by wumke** [comment]
There have been various issues and workarounds in the past (and it works on all my tested devices), since this is another project issue I suggest you post all your relevant data in an issue there (RN version, lib version, platform version, app in background or completely closed...). 
You may reference the issue here for future searches.
