### ISSUE TITLE
Crashes when notification time reached

### ISSUE THREAD

**Issue by yalcinozer** [wumke/react-native-local-notifications#30]
Using react native version 0.59
I defined a notification as shown below then wait it to be displayed but app crashes.
RNLocalNotifications.createNotification(1, 'Some text', '2019-09-07 23:15', 'default');

**Comment by wumke** [comment]
Library installed directly from github or via npm? (github master branch always contains latest chages, npm version may not be updated...)
Android or iOS?
Can you check the logs in Xcode or Android Studio? That should tell you the problem!

**Comment by yalcinozer** [comment]
I installed it by github today. I also tried on device (Android 5.0 LG d855) beside genymotion emulator. App on emulator crashed again, device give a sound on time but notification didn't appear on screen. I actually dont have any experiences about Android Studio. I will let you know if I see any errors. Thanks.

**Comment by wumke** [comment]
Note that the readme mentions:

> NOTIFICATIONS WILL NOT BE SHOWN WHEN YOUR APP IS IN THE FOREGROUND.

You say Android real device with 5.0, which version was your emulator?

**Comment by wumke** [comment]
If you leave your phone (or android studio emulator) connected and the log open while the app is in background you should see the problem there, with a bit of luck it will even tell you in which file on which line (java files).

**Comment by yalcinozer** [comment]
I tried on emulator 5.0. Results on same on my device. I also realised that there is a clock icon on status bar as if I set up an alarm. Then it disappears when notification sound heard but no notification displayed again. I added a screen capture. Thanks. Device didnt show any error mesages by the way.

[screencast-Genymotion-2019-09-11_17.54.31.818.zip](https://github.com/wumke/react-native-local-notifications/files/3601406/screencast-Genymotion-2019-09-11_17.54.31.818.zip)

**Comment by wumke** [comment]
Are you using androidX? Then can you try and change the import in AlarmReceiver.java from

> import android.support.v4.app.NotificationCompat;

to

> import androidx.core.app.NotificationCompat;

**Comment by brycecorbitt** [comment]
Though I'm running an emulator on Android 8.1, I believe I'm encountering the same issue. I created a test notification with the same arguments above, and it crashes when the time is reached.
I managed to get a log of the crash and found this:

`
AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.github.wumke.RNLocalNotifications.AlarmReceiver: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): 
`

It looks like it's failing to use the default icon values. I tried calling `RNLocalNotifications.setAndroidIcons("ic_launcher", "mipmap", "notification_small", "drawable");
`  to see if it needed to be explicitly called, but it didn't make a difference.

It's worth noting that my project is using React Native 0.60.5, and AlarmReceiver.java has the correct import because I've configured the project with [Jetifier](https://www.npmjs.com/package/jetifier).

**Comment by wumke** [comment]
@brycecorbitt : Nice you figured out how to fix your problem. Indeed, the small icons are not included by default since they are project specific... nice link for quick icon generation, I'll put that link in the readme!

@yalcinozer : Could this also be your problem??

**Comment by yalcinozer** [comment]
> @brycecorbitt : Nice you figured out how to fix your problem. Indeed, the small icons are not included by default since they are project specific... nice link for quick icon generation, I'll put that link in the readme!
> 
> @yalcinozer : Could this also be your problem??

This solution may works for me also. I will try it. So I'm closing issue for now, If I have any problem, I contact to you, thanks.
